name: Label issues
on:
  pull_request

jobs:
  label_bug:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.head_ref, 'fix/')
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{github.token}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["bug"]
            })
  label_feature:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{github.token}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["enhancement"]
            })
