name: Pull Request

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ignore approval by bot (re-request)
      uses: actions/github-script@v6
      with:
        github-token: ${{github.token}}
        script: |
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])

          github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pull_number,
            reviewers: ["github-actions"]
          })

    - name: Try to fail
      run: |
        # sleep 100
        exit 0

    - name: if fail
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body:"Failed",
            event: "REQUEST_CHANGES"
          })
      if: failure()

    - name: if success
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body:"Succeed",
            event: "APPROVE"
          })
      if: success()
